# Generated by Django 4.2.3 on 2023-07-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("extractor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractedInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("metadata", models.JSONField()),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extractor.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
