# Generated by Django 4.2.3 on 2023-07-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractor", "0002_extractedinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedinfo",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extractedinfo",
            name="slide_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
