# Generated by Django 4.2.3 on 2023-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extractor", "0003_alter_extractedinfo_metadata_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extractedinfo",
            old_name="slide_title",
            new_name="title",
        ),
        migrations.AddField(
            model_name="extractedinfo",
            name="no_of_pages",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
